title: Marten Analyzers
description: Roslyn analyzers for Marten
collections:
  rules:
    output: true
defaults:
  - scope:
      path: ""
      type: "rules"
    values:
      layout: rule
baseurl: /marten.analyzers
repository: jokokko/marten.analyzers
author: Joona-Pekka Kokko
exclude: ["Gemfile*"]
plugins:  
  - jekyll-seo-tag